-- =====================================================
-- Yolmov Dinamik Fiyatlandırma Konfigürasyonu
-- Tarih: 05.12.2025
-- Amaç: Kod değişikliği olmadan fiyat güncellemesi
-- =====================================================

-- Pricing Configuration Tablosu
CREATE TABLE IF NOT EXISTS pricing_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Baz Ücretler
  base_fee DECIMAL(10,2) DEFAULT 1500.00 NOT NULL,
  
  -- Mesafe Limitleri (KM)
  short_distance_limit INT DEFAULT 15 NOT NULL,
  medium_distance_limit INT DEFAULT 100 NOT NULL,
  
  -- KM Başı Ücretler
  short_distance_rate DECIMAL(10,2) DEFAULT 0.00 NOT NULL, -- İlk 15 KM için ekstra ücret yok
  medium_distance_rate DECIMAL(10,2) DEFAULT 50.00 NOT NULL, -- 16-100 KM arası
  long_distance_rate DECIMAL(10,2) DEFAULT 33.00 NOT NULL, -- 100+ KM
  
  -- Zaman Çarpanları
  night_multiplier DECIMAL(3,2) DEFAULT 1.25 NOT NULL, -- 22:00-06:00
  weekend_multiplier DECIMAL(3,2) DEFAULT 1.10 NOT NULL, -- Hafta sonu
  
  -- Araç Tipi Çarpanları
  sedan_multiplier DECIMAL(3,2) DEFAULT 1.00 NOT NULL,
  suv_multiplier DECIMAL(3,2) DEFAULT 1.15 NOT NULL,
  minibus_multiplier DECIMAL(3,2) DEFAULT 1.30 NOT NULL,
  luxury_multiplier DECIMAL(3,2) DEFAULT 1.20 NOT NULL,
  
  -- Durum Çarpanları
  broken_vehicle_multiplier DECIMAL(3,2) DEFAULT 1.15 NOT NULL, -- Arızalı araç
  ditch_multiplier DECIMAL(3,2) DEFAULT 2.00 NOT NULL, -- Şarampole düşmüş
  accident_multiplier DECIMAL(3,2) DEFAULT 1.25 NOT NULL, -- Kaza durumu
  
  -- Ek Hizmet Çarpanları
  has_load_multiplier DECIMAL(3,2) DEFAULT 1.10 NOT NULL, -- Yük taşıma
  urgent_multiplier DECIMAL(3,2) DEFAULT 1.30 NOT NULL, -- Acil çekme (timing: 'now')
  
  -- Esneklik Marjı (Fiyat Aralığı için)
  price_flexibility_percent DECIMAL(5,2) DEFAULT 5.00 NOT NULL, -- %5 (+/-)
  
  -- Meta
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_by TEXT, -- Admin kullanıcı ID'si
  notes TEXT -- Güncelleme sebepleri için
);

-- Varsayılan Konfigürasyon
INSERT INTO pricing_config (
  base_fee,
  short_distance_limit,
  medium_distance_limit,
  short_distance_rate,
  medium_distance_rate,
  long_distance_rate,
  night_multiplier,
  weekend_multiplier,
  sedan_multiplier,
  suv_multiplier,
  minibus_multiplier,
  luxury_multiplier,
  broken_vehicle_multiplier,
  ditch_multiplier,
  accident_multiplier,
  has_load_multiplier,
  urgent_multiplier,
  price_flexibility_percent,
  is_active,
  notes
) VALUES (
  800.00, -- Açılış ücreti (1500 → 800)
  15, -- Kısa mesafe limiti
  100, -- Orta mesafe limiti
  0.00, -- İlk 15 KM ekstra ücret yok
  25.00, -- 16-100 KM arası (50 → 25)
  15.00, -- 100+ KM (33 → 15)
  1.15, -- Gece çarpanı (1.25 → 1.15)
  1.05, -- Hafta sonu (1.10 → 1.05)
  1.00, -- Sedan (normal)
  1.10, -- SUV (1.15 → 1.10)
  1.20, -- Minibüs (1.30 → 1.20)
  1.15, -- Lüks (1.20 → 1.15)
  1.10, -- Arızalı (1.15 → 1.10)
  2.00, -- Şarampol (kritik - değişmedi)
  1.20, -- Kaza (1.25 → 1.20)
  1.05, -- Yük (1.10 → 1.05)
  1.20, -- Acil (1.30 → 1.20)
  100.00, -- Fiyat esnekliği (5% → 100% margin)
  TRUE,
  'Gerçekçi fiyatlandırma: İvrindi-Tavşanlı 120KM = ~11.000 TL hedef'
);

-- Otomatik güncelleme timestamp trigger
CREATE OR REPLACE FUNCTION update_pricing_config_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pricing_config_updated
BEFORE UPDATE ON pricing_config
FOR EACH ROW
EXECUTE FUNCTION update_pricing_config_timestamp();

-- Route Cache Tablosu (B Planı: Performans Optimizasyonu)
CREATE TABLE IF NOT EXISTS route_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Konum Bilgileri (Hashed Key)
  route_hash TEXT UNIQUE NOT NULL, -- MD5(start_lat,start_lng,end_lat,end_lng)
  
  start_lat DECIMAL(10,7) NOT NULL,
  start_lng DECIMAL(10,7) NOT NULL,
  end_lat DECIMAL(10,7) NOT NULL,
  end_lng DECIMAL(10,7) NOT NULL,
  
  -- OSRM Sonuçları
  distance_km DECIMAL(8,2) NOT NULL,
  duration_seconds INT NOT NULL,
  route_geometry JSONB, -- Polyline koordinatları
  
  -- Cache Yönetimi
  hit_count INT DEFAULT 1,
  last_used_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now() + interval '30 days')
);

-- Cache indexleri
CREATE INDEX idx_route_cache_hash ON route_cache(route_hash);
CREATE INDEX idx_route_cache_expires ON route_cache(expires_at);

-- Eski cache kayıtlarını temizleme (Cron job ile çağrılabilir)
CREATE OR REPLACE FUNCTION cleanup_expired_route_cache()
RETURNS INT AS $$
DECLARE
  deleted_count INT;
BEGIN
  DELETE FROM route_cache
  WHERE expires_at < timezone('utc'::text, now());
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- Row Level Security (RLS) Policies
-- =====================================================

-- Pricing config: Herkes okuyabilir, sadece admin yazabilir
ALTER TABLE pricing_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access for pricing_config"
ON pricing_config FOR SELECT
TO public
USING (is_active = TRUE);

CREATE POLICY "Admin full access for pricing_config"
ON pricing_config FOR ALL
TO authenticated
USING (auth.jwt() ->> 'role' = 'admin')
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- Route cache: Public okuma/yazma (Cache amacıyla)
ALTER TABLE route_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for route_cache"
ON route_cache FOR ALL
TO public
USING (TRUE)
WITH CHECK (TRUE);

COMMENT ON TABLE pricing_config IS 'Dinamik fiyatlandırma motor konfigürasyonu. Admin panelden güncellenebilir.';
COMMENT ON TABLE route_cache IS 'OSRM rota hesaplamaları cache. 30 gün TTL.';
